version: 2
updates:
  - package-ecosystem: "github-actions"
    # default location of ".github/workflows"
    directory: ''
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    # target-branch: "develop"
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "nuget"
    # location of package manifests
    directory: 'src/Adapter/MSTest.CoreAdapter/'
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "nuget"
    # location of package manifests
    directory: 'src/Adapter/PlatformServices.Desktop/'
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "nuget"
    # location of package manifests
    directory: 'src/Adapter/PlatformServices.Interface/'
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "nuget"
    # location of package manifests
    directory: 'src/Adapter/PlatformServices.NetCore/'
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "nuget"
    # location of package manifests
    directory: 'src/Adapter/PlatformServices.Portable/'
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "nuget"
    # location of package manifests
    directory: 'src/Adapter/PlatformServices.Universal/'
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "nuget"
    # location of package manifests
    directory: 'src/Adapter/PlatformServices.WinUI/'
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "nuget"
    # location of package manifests
    directory: 'src/TestFramework/Extension.Core/'
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "nuget"
    # location of package manifests
    directory: 'src/TestFramework/Extension.Desktop/'
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "nuget"
    # location of package manifests
    directory: 'src/TestFramework/Extension.UWP/'
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "nuget"
    # location of package manifests
    directory: 'src/TestFramework/Extension.WinUI/'
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: "nuget"
    # location of package manifests
    directory: 'src/TestFramework/MSTest.Core/'
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)
